import React, { Component } from 'react'
import logo from '../assets/Octocat.png'
import User from '../components/User'
import Projects from '../components/Projects'
import { getUsername } from '../Utils'
import _ from 'lodash'

class Home extends Component {
  constructor(props) {
    super(props)
    this.state = {
      languageColours: {},
      languages: [],
      topics: []
    }
  }

  componentDidMount() {
    document.title = "Octopocto: " + getUsername() + "'s Portfolio"

    // fetch language colours
    fetch('https://raw.githubusercontent.com/ozh/github-colors/master/colors.json')
    .then(res => res.json())
    .then(json => this.setState({languageColours: json}))
  }

  render() {
    if(getUsername()===null) {
      return (
        <div className="No-user">
          <h3>Go to <a href="https://sekaru.github.io/Octopocto/?user=sekaru">sekaru.github.io/octopocto/?user=[username]</a> to look at a generated portfolio!</h3>
        </div>
      )
    }

    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1>{getUsername()}'s Portfolio</h1>
        </header>
        
        <User languageColours={this.state.languageColours} favLanguages={this.getFavs(this.state.languages)} favTopics={this.getFavs(this.state.topics)} />
        <Projects languageColours={this.state.languageColours} addLanguages={this.addLanguages} addTopics={this.addTopics} />

        <footer>
          <h3>Generated by <a style={{color: "black"}} href="https://github.com/sekaru/octopocto">Octopocto</a>!</h3>
        </footer>
      </div>
    );
  }

  addLanguages = (newLanguages) => {
    let languages = this.state.languages
    newLanguages.forEach(language => {
      let dupe = _.find(languages, {name: language})
      if(dupe) {
        dupe.count++
      } else {
        languages.push({name: language, count: 1})
      }
    })

    this.setState({languages})
  }

  addTopics = (newTopics) => {
    let topics = this.state.topics
    newTopics.forEach(topic => {
      let dupe = _.find(topics, {name: topic})
      if(dupe) {
        dupe.count++
      } else {
        topics.push({name: topic, count: 1})
      }
    })

    this.setState({topics})
  }

  getFavs(data) {
    return data.sort((a, b) => {
      return a.count === b.count ? 0 : a.count > b.count ? -1 : 1
    }).slice(0, 5)
  }
}

export default Home