import React, { Component } from 'react'
import User from '../components/User'
import Projects from '../components/Projects'
import { getUsername, titleCase } from '../Utils'
import _ from 'lodash'
import NoUser from '../components/NoUser'
import Header from '../components/Header'

class Home extends Component {
  constructor(props) {
    super(props)
    this.state = {
      languageColours: {},
      languages: [],
      topics: []
    }
  }

  componentDidMount() {
    // fetch language colours
    fetch('https://raw.githubusercontent.com/ozh/github-colors/master/colors.json')
    .then(res => res.json())
    .then(json => this.setState({languageColours: json}))
  }

  render() {
    if(!getUsername()) {
      return (
        <NoUser/>
      )
    }

    return (
      <div className="App">
        <Header title={titleCase(getUsername()) + "'s Portfolio"} />
        <User languageColours={this.state.languageColours} favLanguages={this.getFavs(this.state.languages)} favTopics={this.getFavs(this.state.topics)} />
        <Projects languageColours={this.state.languageColours} addLanguages={this.addLanguages} addTopics={this.addTopics} />

        <footer>
          <h3>Generated by <a className="Link" href="https://github.com/sekaru/octopocto">Octopocto</a></h3>
        </footer>
      </div>
    )
  }

  addLanguages = (newLanguages) => {
    let languages = this.state.languages
    newLanguages.forEach(language => {
      let dupe = _.find(languages, {name: language})
      if(dupe) {
        dupe.count++
      } else {
        languages.push({name: language, count: 1})
      }
    })

    this.setState({languages})
  }

  addTopics = (newTopics) => {
    let topics = this.state.topics
    newTopics.forEach(topic => {
      let dupe = _.find(topics, {name: topic})
      if(dupe) {
        dupe.count++
      } else {
        topics.push({name: topic, count: 1})
      }
    })

    this.setState({topics})
  }

  getFavs(data) {
    return data.sort((a, b) => {
      return a.count === b.count ? 0 : a.count > b.count ? -1 : 1
    }).slice(0, 5)
  }
}

export default Home